# If updating this file, please also review `docs/release-process.md`
# (in the contentauth/c2pa-rs repo) and
# `.github/workflows/pr_title.yml` and update the summary of these rules
# in those files accordingly.

rules:
  # Body may be empty
  body-empty:
    level: ignore

  # Description must not be empty
  description-empty:
    level: error

  # Description should be <70 chars
  description-max-length:
    level: warning
    length: 70

  # Scope is not allowed
  scope:
    level: error
    optional: false
    options: []

  # Subject line should exist
  subject-empty:
    level: error

  # Type must be one of these options
  type:
    level: error
    options:
      - build
      - chore
      - ci
      - docs
      - feat
      - fix
      - perf
      - refactor
      - revert
      - style
      - test
      - update
